# Generated by Django 5.0.3 on 2024-05-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_product_manufactured_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="manufactured_at",
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.PositiveIntegerField(
                help_text="Введите стоимость продукта",
                verbose_name="Стоимость продукта",
            ),
        ),
    ]
