# Generated by Django 5.0.3 on 2024-06-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_remove_product_manufactured_at_alter_product_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        auto_created=True,
                        blank=True,
                        help_text="Введите Дату создания",
                        null=True,
                        verbose_name="Дата создания (записи в БД)",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите заголовок статьи",
                        max_length=100,
                        verbose_name="Заголовок статьи",
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="slug"
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="Введите текст статьи",
                        null=True,
                        verbose_name="Содержимое статьи",
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите изображение",
                        null=True,
                        upload_to="media/photo",
                        verbose_name="Превью",
                    ),
                ),
                ("is_publication", models.BooleanField(default=True)),
                ("views_count", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
