# Generated by Django 5.0.3 on 2024-06-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_blog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "ordering": ["title"],
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
        migrations.AlterField(
            model_name="blog",
            name="is_publication",
            field=models.BooleanField(default=True, verbose_name="опубликовано"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="views_count",
            field=models.PositiveIntegerField(default=0, verbose_name="просмотры"),
        ),
    ]
